### ISSUE TITLE
Allow to ignore params, or use willdcard or regex to select source request

### ISSUE THREAD

**Issue by BorisNaguet** [arai-a/ditm#13]
Hi,

I wanted to rewrite the response of an XHR request that looks like:
`https://www.site.com/file.json?timestamp=1588588185145`
but the timestamp is obviously different each time.

I tried with '.json*', '.json.*', ect...

It would be nice to have a way to use wildcard to select source URL

**Comment by arai-a** [comment]
Thank you for your suggestion :)
Fixed in Ver.1.4.0, with both wildcard and forward match.
