### ISSUE TITLE
[feature] Point to a local file on the computer

### ISSUE THREAD

**Issue by karlcow** [arai-a/ditm#2]
It would be useful for people who are using a code editor with more capabilities.

**Comment by arai-a** [comment]
Good idea, and surely this is better when handling large file.

But unfortunately this is not possible with WebExtensions API, except using [Native Messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging).

The requirements here are:

  - Read local file (required)
    - WebExtensions API doesn't provide direct access to local file
  - Monitor file modification (optional)
    - Without this, users need to click "reload this file" button every time after saving the file

I'll look into Native Messaging to see if it's easy enough to implement
(I'm worrying especially about installation part)

**Comment by karlcow** [comment]
would it be possible to replace with a http://localhost/blah.js
Because it would be easy for me to start a local Web server. and edit this file locally.

**Comment by arai-a** [comment]
Interesting idea :)
fixed in https://github.com/arai-a/ditm/commit/dded7601f4f37d0e97c58c6f24626090c91f1d13

I've uploaded it as version 1.1.4 on AMO.

also available from https://github.com/arai-a/ditm/releases/tag/1.1.4
